name: Fetch accessions
on: [push]
  # schedule:
  #   # Run every day at midnight
  #   - cron: '0 0 * * *'
jobs:
  test:
    name: Fetch
    runs-on: ubuntu-18.04
    # Check if the event is not triggered by a fork
    # Comment the next line if you want to get automated accession updates in your fork
    # if: github.repository == 'galaxyproject/SARS-CoV-2'
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pysradb
      run: pip install https://github.com/saketkc/pysradb/archive/master.zip requests
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
    - name: Fetch accessions
      run: ./fetch_sra_acc.sh
      working-directory: ./genomics/4-Variation/
    - name: Show differences
      run: 'git diff --stat && git diff'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update SARS-CoV-2 accessions"
        title: "Daily update of SARS-CoV-2 accessions"
        body: "Automated updates of SARS-CoV-2 accessions"
        labels: Automation
        branch: accession_updates
        base: master
